// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mcxryjlhvrgtymwvdbki.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1jeHJ5amxodnJndHltd3ZkYmtpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4NjEzMDIsImV4cCI6MjA2OTQzNzMwMn0.F38OV1Zfp1t0GaHNaGpdR3kvAipknSohuuSkbhGVNPk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});